### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by jrstarke** [awslabs/aws-cloudfront-samples#2]
I'm putting together a repository of open source Lambda functions, and since I use this function, I was hoping to include it. I'm a little confused about the licensing on it through, because the LICENSE.txt says Apache 2.0, the NOTICE.txt says All Rights Reserved, and the update_security_groups_lambda/update_security_groups.py says both.

**Comment by hyandell** [comment]
Hi Jamie,

The samples are Apache 2.0 licensed. Starting with "All Rights Reserved" and then having the licensing is stylistic (I've seen it with corporations but not with the foundations).
